# Generated by Django 5.2.10 on 2026-01-22 17:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('secret', models.TextField()),
                ('expires_at', models.DateTimeField()),
                ('is_viewed', models.BooleanField(default=False)),
            ],
        ),
    ]
